### ISSUE TITLE
CR Overlay Transparent Image fails with "module 'PIL.Image' has no attribute 'ANTIALIAS'" when using PIL 10.2, Antialias attribute needs renaming

### ISSUE THREAD

**Issue by aegis72** [Suzie1/ComfyUI_Comfyroll_CustomNodes#103]
It seems that this attribute has been removed in Pillow 10.x; I downgraded back to 9.5 and it works again. 

Error occurred when executing CR Overlay Transparent Image:
fyroll_CustomNodes\nodes\nodes_graphics_layout.py", line 522, in overlay_image
    overlay_image = overlay_image.resize(new_size, Image.ANTIALIAS)
module 'PIL.Image' has no attribute 'ANTIALIAS'

BG Info I found: 
"ANTIALIAS was removed in Pillow 10.0.0 (after being deprecated through many previous versions). Now you need to use PIL.Image.LANCZOS or PIL.Image.Resampling.LANCZOS.

(This is the exact same algorithm that ANTIALIAS referred to, you just can no longer access it through the name ANTIALIAS.)

Reference: [Pillow 10.0.0 release notes (with table of removed constants)](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants)"

**Comment by Suzie1** [comment]
hi, thanks for reporting this
its a quick fix, i'll include in the next update
Suzie

**Comment by aegis72** [comment]
You're amazing, thanks!

**Comment by Suzie1** [comment]
fixed in version: 1.71.1
Suzie
