### ISSUE TITLE
[Bug][Wiki] Example workflows in wiki not pointing to existing files

### ISSUE THREAD

**Issue by TFWol** [Suzie1/ComfyUI_Comfyroll_CustomNodes#104]
The issue is a `_v` is in front of the numbers

Example page:
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki/List-Nodes

Wiki points to:
`https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/workflows/List/CR_Text_List_demo_v2.json`

Actual file:
`https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/workflows/List/CR_Text_List_demo2.json`

**Comment by Suzie1** [comment]
Apologies, I think there are more broken links. I'll try get them fixed today.
Thanks for reporting this.
Suzie

**Comment by Suzie1** [comment]
fixed in 1.73.1
