### ISSUE TITLE
Does the blacklist support multiple keywords and what is the format?

### ISSUE THREAD

**Issue by whmc76** [Suzie1/ComfyUI_Comfyroll_CustomNodes#112]
Does the blacklist support multiple keywords and what is the format?

**Comment by Suzie1** [comment]
The blacklist is intended to be for simple keyword lists such as:
blue
chair
elephant

However, word strings also work, e.g.:
blue chair
large blue elephant

I need to add handling for an empty blacklist
I could also add stripping of trailing commas for csv lists

hope this helps
Suzie

**Comment by Suzie1** [comment]
i just did some tests and see there was a bug with multiple keywords, this is fixed in v1.75.1
thanks for reporting this
Suzie

**Comment by whmc76** [comment]
> i just did some tests and see there was a bug with multiple keywords, this is fixed in v1.75.1 thanks for reporting this Suzie

good job
