### ISSUE TITLE
[Discussion/Feature Request] Prescale for aspect ratio node?

### ISSUE THREAD

**Issue by vanillacode314** [Suzie1/ComfyUI_Comfyroll_CustomNodes#56]
Basically the idea is to have a new float input which will be multiplied to output width / height / latent dimensions.

Why? With the release of deep shrink kohya method, it would be nice to scale the output without using custom values.

I can make a PR for this if you agree

**Comment by Suzie1** [comment]
yes, that sounds interesting, please do the PR if you have time, Suzie
