### ISSUE TITLE
[BUG] Pattern generators' output can't be merged to other `image` outputs

### ISSUE THREAD

**Issue by Lex-DRL** [Suzie1/ComfyUI_Comfyroll_CustomNodes#62]
Steps to reproduce (just load the attached workflow):
- make an initial generation (with the built-in `KSampler` node)
- decode it from latent space (again, with the built-in node)
- 👉🏻 generate a radial ramp for a simple vignette with the same dimentions (with `CR Radial Gradient`)
- try to multiply them (with a built-in `ImageBlend`, too)

and here's the error I get:
```
Error occurred when executing ImageBlend:

The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 3

  File "E:\SD\ComfyUI-portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\SD\ComfyUI-portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\SD\ComfyUI-portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\SD\ComfyUI-portable\ComfyUI\comfy_extras\nodes_post_processing.py", line 41, in blend_images
    blended_image = self.blend_mode(image1, image2, blend_mode)
  File "E:\SD\ComfyUI-portable\ComfyUI\comfy_extras\nodes_post_processing.py", line 50, in blend_mode
    return img1 * img2
```

What's weird, if I just encode the node's output to latent and decode it back as image right away, the error doesn't pop up.
Here's the test case workflow:
![Test case](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/3897975/7576c34c-efbf-4b4e-bd63-b50cbac3db2d)

**Comment by Suzie1** [comment]
hi, thanks for reporting this,
another user also reported an error.
Thanks for sending the test case,
I hope to have a fix soon
Suzie

**Comment by Suzie1** [comment]
Hello, I expanded my test cases and have a simple fix that works accross all cases now. It will be deployed later today.

Thank you very much for providing this workflow. It helped a lot in isolating this issue.

Some nodes were outputting in RGBA which is not accepted as an input on all nodes. I have now switched to RGB output accross all my graphics nodes.

Suzie

**Comment by Suzie1** [comment]
the fix is released, now closing
