### ISSUE TITLE
odd behavior of string to combo node - functions okay so maybe not an issue but

### ISSUE THREAD

**Issue by EricRollei** [Suzie1/ComfyUI_Comfyroll_CustomNodes#63]
![image](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/97568200/160088e1-bc5e-41d0-82c4-83a04f32e9d0)

Here's a picture of a graph I'm working on.   yesterday I had another browser tab open and was working on a different workflow.  Today I noticed that I have pictures from that other workflow displayed in the String to Combo node itself.  I use the String to Combo node in several places in this workflow, but this one location shows the images while the others don't.  I have no idea why, just sharing in case this is something important.   You can see from the show string node that the String to Combo Node is functioning correctly and passing the string and not the images, but how did it get the images from another workflow and store them?

**Comment by Suzie1** [comment]
i'll close this for now, but keep an eye out for the issue
thanks for reporting it
