### ISSUE TITLE
String to Float doesn't work with negative numbers

### ISSUE THREAD

**Issue by fidecastro** [Suzie1/ComfyUI_Comfyroll_CustomNodes#64]
As per the title. Any negative number gets the following error message:

Error occurred when executing CR String To Number:

local variable 'int_out' referenced before assignment

  File "/workspace/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/workspace/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/workspace/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/conversion.py", line 38, in convert
    return (int_out, float_out, show_help,)
Queue size: 0
Extra options

**Comment by Suzie1** [comment]
hi, i did a fix that will be in the next update,
it handles negative numbers now
i also added rounding rules for integers
it uses the round to positive infinity method and not rounding towards zero
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki/Conversion-Nodes/_edit#cr-string-to-number

**Comment by Suzie1** [comment]
fixed in PR70, also added rounding rules
