### ISSUE TITLE
Error trying to use Simple Text Watermark node, can't find fonts

### ISSUE THREAD

**Issue by BaconIsAVeg** [Suzie1/ComfyUI_Comfyroll_CustomNodes#72]
![image](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/139648009/c5767e85-74b6-49c8-a16a-1754af50b9c8)

![image](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/139648009/a3c3bef4-5a6d-41a4-8ccb-e73840b58fc0)

I see that the fonts are part of the node structure, I've even tried installing them into the system font cache.  This is a Comfy server running on Linux.

Is it perhaps looking for a physical file in the wrong path?

**Comment by Suzie1** [comment]
Many thanks for flagging this, 
It may be having problems with the linux file structure, i think i have a fix for it that i used on another node.
I'll make the change in the next update and then ask you to test it.
Suzie

**Comment by BaconIsAVeg** [comment]
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/pull/73

**Comment by BaconIsAVeg** [comment]
> Many thanks for flagging this, It may be having problems with the linux file structure, i think i have a fix for it that i used on another node. I'll make the change in the next update and then ask you to test it. Suzie

 I poked at it and submitted a PR, works on Linux, can't test on a windows machine though.

**Comment by BaconIsAVeg** [comment]
Issue resolved with PR#73.
