### ISSUE TITLE
conversion.py issue with String to Integer

### ISSUE THREAD

**Issue by fidecastro** [Suzie1/ComfyUI_Comfyroll_CustomNodes#77]
@Suzie1 it seems the def convert is missing the round_integer call for the CR String to Number call. I'm working around it by just adding round_integer = "round_up" in the function call.

**Comment by Suzie1** [comment]
Oh sorry, i may have missed something in my test cases. I will check it tomorrow.
Thanks for reporting it. Suzie

**Comment by Suzie1** [comment]
hi, I retested the node today with my test cases and couldn't see a problem
Https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki/Conversion-Nodes#cr-string-to-number
I may be missing something
Please can you let me know your scenario, the expected result, and the actual result
thanks
Suzie

**Comment by fidecastro** [comment]
Maybe it was an issue with already existing workflows? The workflows were bricked because the conversion node took 1 more positional arguments than it was being given (the offending one being the round_integer argument).

**Comment by Suzie1** [comment]
Yes, that may be the explanation, when parameters are added to a node they
often need reloading. Try deleting the node and replacing it again. Let me
know if this works.

**Comment by fidecastro** [comment]
Will do. Thanks!

**Comment by Suzie1** [comment]
hi, i'm cloing this for now, if the issue reoccurs please let me know
