### ISSUE TITLE
Import Custom Nodes Fail after an update v1.47 Dec 23, 2023

### ISSUE THREAD

**Issue by Ketorami** [Suzie1/ComfyUI_Comfyroll_CustomNodes#82]
![Screenshot 2023-12-24 061518](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/101268214/3accd637-4945-4b6f-9313-614177f052c3)

![Screenshot 2023-12-24 062443](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/101268214/89036f94-856e-42b0-bfe5-05b5c8a03ade)

![Screenshot 2023-12-24 062225](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/101268214/c2181109-1ff0-4d09-9f9b-eafb632de355)

![Screenshot 2023-12-24 062617](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/101268214/746774e7-3f49-446e-a910-4f71e9459a0f)

**Comment by Suzie1** [comment]
thank you, i think the error message may help me find the issue, i'm working on this now

**Comment by Suzie1** [comment]
Hi, I just pushed a quite fix on the init file
Please can you retest?
Suzie

**Comment by Suzie1** [comment]
Thanks for checking it! I'll leave this open for now in case anyone else has any problems.
