### ISSUE TITLE
Cannot import ComfyUI_Comfyroll_CustomNodes: No module named 'pywavefront'

### ISSUE THREAD

**Issue by krahnikblis** [Suzie1/ComfyUI_Comfyroll_CustomNodes#87]
looks like the commit 2 weeks ago added a dependency in dev_nodes/dev_pil_3D.py. i don't see a requirements file (at least in the limited formats i'm familiar with) so i'm not sure how to adjust the code myself to make Comfy auto-install pywavefront. i'm running inside of a Stable Swarm Docker container, so it's not a simple thing to install dependencies manually. hoping for a patch to this lib to enable a reinstall from Comfy Manager 

thanks!

**Comment by Suzie1** [comment]
hello, sorry this is giving problems, i'll remove that depenency tonight
it was experimental

**Comment by Suzie1** [comment]
hi, i have removed the dependency
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/dev_nodes/dev_pil_3D.py

**Comment by Suzie1** [comment]
closing, let me know if its still an issue
