### ISSUE TITLE
NameError: name 'io' is not defined

### ISSUE THREAD

**Issue by alessandroperilli** [Suzie1/ComfyUI_Comfyroll_CustomNodes#89]
The (very powerful) CR Multiline Text node generates this error upon execution of the queue:

>   File "/ComfyUI/execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes.py", line 467, in text_multiline
>     for line in io.StringIO(text):
>             ^^
> NameError: name 'io' is not defined

Thank you

**Comment by Suzie1** [comment]
thanks for reporting this!
i checked the imports and it does include this line
`from io import BytesIO, StringIO`
there must be another issue, i'll do some testing
did the node work in other scenarios? what scenario sparked the error?
Suzie

**Comment by Suzie1** [comment]
don't worry, i found the error, will try push a fix this afternoon

**Comment by Suzie1** [comment]
fixed now, you can re-update

**Comment by alessandroperilli** [comment]
It works fine now, thank you!
