### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 14643363840 bytes.

### ISSUE THREAD

**Issue by bihailantian655** [Suzie1/ComfyUI_Comfyroll_CustomNodes#92]
DefaultCPUAllocator: not enough memory: you tried to allocate 14643363840 bytes.   

enlarge a 512*900 picture 1  or 4 times bigger， need  the same size of  video card 
memory 。      a total of   physical  video card  8g  memory  + 1 g of shared memory. 

After batch enlargement, combine video failure ，requires a lot of memory.  get  this  error         DefaultCPUAllocator: not enough memory: you tried to allocate 14643363840 bytes.

My video card is 8g.

![588a44bee777bcd7c832c3af08a9cee7](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/35267721/eb343c07-caf6-4c49-b07b-646d14ed794f)

What does resize widith mean

**Comment by Suzie1** [comment]
hi, i'll look at the memory problem, thanks for reporting it
resize_width can you used if you select the resize mode, the output image will be resized the the resize-width keeping the same aspect ratio.
Suzie

**Comment by bihailantian655** [comment]
use   esrgan 4x  get  this  error    not  4k  ultral  sharp ，

**Comment by Suzie1** [comment]
Hi, I don't have a specific fix for this. My suggestion is that you debatch the images before passing them to the upscaler using CR Debatch Frames or ImageBatchToList. Suzie

**Comment by bihailantian655** [comment]
> Hi, I don't have a specific fix for this. My suggestion is that you debatch the images before passing them to the upscaler using CR Debatch Frames or ImageBatchToList. Suzie

Thanks
