### ISSUE TITLE
[Feature Request] module input/output update

### ISSUE THREAD

**Issue by Rvage0815** [Suzie1/ComfyUI_Comfyroll_CustomNodes#95]
hello,
i would be happy if i could send some user-defined data with the pipe of cr module input/output, e.g. strings and integer. i personally would need 2 strings and 3 integer to send them through the workflow and would then no longer have to switch to setnode/getnode from kj which makes the workflow rather messy. :) kind regards.

**Comment by Suzie1** [comment]
Hello, Thanks for this suggestion.
I'm planning to add some new pipe types soon.
One would be a flexible data pipe that the user could add any set of parameters to.
And the other would be 4/8/16/32 channel pipes that carry a float or text data types.
Another user is requesting these, so it could get done in the next week.
Suzie

**Comment by Rvage0815** [comment]
that sounds promising. does that mean another new pipe to the current one or will it be extended? it would be pretty cool if it worked like impactswitch for example. there is an input that is of the type any and when you connect something, this input changes to the corresponding type and a new empty input appears. in the example the new input would be of the same type, but more useful would be one of the type any again so that you can connect something else. that's certainly not easy i could imagine :P

**Comment by Suzie1** [comment]
hi, i just added 4 new bus nodes that handle any_type
i'll close this for now, but feel free to raise another feature request if anything is missing
Suzie

**Comment by Rvage0815** [comment]
i like it thank you very much :)
