### ISSUE TITLE
SDXL Aspect Ratio

### ISSUE THREAD

**Issue by ThatGlennD** [Suzie1/ComfyUI_Comfyroll_CustomNodes#99]
CR SDXL Aspect Ratio lists 832x1216 at 5:8 when it's generally accepted that this ratio if 2:3

**Comment by Amorano** [comment]
> CR SDXL Aspect Ratio lists 832x1216 at 5:8 when it's generally accepted that this ratio if 2:3

11 x 16 is closer.

**Comment by ThatGlennD** [comment]
> > CR SDXL Aspect Ratio lists 832x1216 at 5:8 when it's generally accepted that this ratio if 2:3
> 
> 11 x 16 is closer.

While it may be "closer" 2:3 and 3:2 are the aspect ratios generally accepted by on demand printing services.  Here's what bard.google.com had to say:

"The aspect ratio of 832x1216 for poster printing is 2:3.

 This is a common aspect ratio for posters, as it's quite versatile and fits well with many standard poster sizes. Here's a breakdown:

Aspect ratio: It's the proportional relationship between the width and height of an image. In this case, 832 (width) divided by 1216 (height) equals 2/3.
Standard poster sizes: Many common poster sizes use a 2:3 aspect ratio, such as 12x18, 18x27, 24x36, and 36x54 inches."

I brought this up because CR SDXL aspect ration list 1216x832 as 3:2 but lists 5:8 as 832x1216 thus a discontinuity in the aspect name.  I use a poster printing service for some of my images, which is why following a standard convention is important to me.  Standards matter.

**Comment by Amorano** [comment]
> > > CR SDXL Aspect Ratio lists 832x1216 at 5:8 when it's generally accepted that this ratio if 2:3
> > 
> > 
> > 11 x 16 is closer.
> 
> While it may be "closer" 2:3 and 3:2 are the aspect ratios generally accepted by on demand printing services. Here's what bard.google.com had to say:
> 
> "The aspect ratio of 832x1216 for poster printing is 2:3.
> 
> This is a common aspect ratio for posters, as it's quite versatile and fits well with many standard poster sizes. Here's a breakdown:
> 
> Aspect ratio: It's the proportional relationship between the width and height of an image. In this case, 832 (width) divided by 1216 (height) equals 2/3. Standard poster sizes: Many common poster sizes use a 2:3 aspect ratio, such as 12x18, 18x27, 24x36, and 36x54 inches."
> 
> I brought this up because CR SDXL aspect ratio lists 1216x832 as 3:2 but lists 5:8 as 832x1216 thus a discontinuity in the aspect name. I use a poster printing service for some of my images, which is why following a standard convention is important to me. Standards matter.

My friend, take a breath. 11x16 is also a standard size for printing.

**Comment by Suzie1** [comment]
@ThatGlennD Can you send a list of standard poster sizes. I can maybe make an Aspect Ratio ISO216 node.

A-series (ISO 216):

A0 (841 x 1189 mm)
A1 (594 x 841 mm)
A2 (420 x 594 mm)
A3 (297 x 420 mm)
A4 (210 x 297 mm)
B-series (ISO 216):

B0 (1000 x 1414 mm)
B1 (707 x 1000 mm)
B2 (500 x 707 mm)
B3 (353 x 500 mm)
B4 (250 x 353 mm)
C-series (ISO 216):

C0 (917 x 1297 mm)
C1 (648 x 917 mm)
C2 (458 x 648 mm)
C3 (324 x 458 mm)
C4 (229 x 324 mm)

Do these look good?
Suzie

**Comment by ThatGlennD** [comment]
I’m out as a witness in a court case at the moment but will look when I get home

**Comment by Suzie1** [comment]
In this case, unless there is serious objection I'll leave the aspect ratio unchanged to avoid imapacting users that have made images using this apect ratio. When old images are opened as a workflow they will error if the description has changed.
This problem may be resolved by Comfy in the future, but I'll close this for now. Suzie
